const path=require('path');
module.exports = {
    devServer:{
        proxy:{
            "/mapi7":{
                target:"http://z.dangdang.com",
                changeOrigin:true
            },
            "/api":{
                target:"http://z.dangdang.com",
                changeOrigin:true
            },
            "/api":{
                target:"http://z.dangdang.com",
                changeOrigin:true
            },
            "/mapi7":{
                target:'http://z.dangdang.com',
                changeOrigin:true
            },
            "/promotion_ajax.php":{
                target:'http://search.m.dangdang.com',
                changeOrigin:true
            },
            "/h5ajax.php":{
                target:'http://product.m.dangdang.com',
                changeOrigin:true
            },
            '/promotion_ajax.php':{
                target:'http://search.m.dangdang.com',
                changeOrigin:true
            },
            '/promotion_ajax.php':{
                target:'http://search.m.dangdang.com',
                changeOrigin:true
            }

        }
    },
    configureWebpack:{
        resolve:{
            alias:{
                "@":path.join(__dirname,'./src'),
                "api":path.join(__dirname,"./src/api"),
                "components":path.join(__dirname,"./src/components"),
                "views":path.join(__dirname,"./src/views"),
                "common":path.join(__dirname,"./src/common"),
                "utils":path.join(__dirname,"./src/utils"),
                "router":path.join(__dirname,"./src/router"),
                "store":path.join(__dirname,"./src/store")
            }
        }
    }
}